#!/bin/sh
set -e

if ! getent group axonmq >/dev/null; then
    addgroup --system axonmq
fi
if ! getent passwd axonmq >/dev/null; then
    adduser --system --ingroup axonmq --no-create-home --shell /bin/false axonmq
fi

mkdir -p /var/lib/axonmq
chown -R axonmq:axonmq /var/lib/axonmq

mkdir -p /var/log/axonmq
chown -R axonmq:axonmq /var/log/axonmq

systemctl daemon-reload
systemctl enable axonmq.service
systemctl start axonmq.service

exit 0