[package]
name = "axonmq"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tokio-stream = "0.1"

async-trait = "0.1"
tracing = "0.1"
bytes = "1"
byteorder = "1"