ARG DEBIAN_VERSION=12
FROM debian:${DEBIAN_VERSION}

USER root

ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install -y tzdata \
    && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get -y update \
    && apt-get -y install \
        sudo pkg-config git gcc g++ openssl libssl-dev clang curl make cmake protobuf-compiler  python3
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:$PATH"
RUN rustup default stable
RUN cargo install cargo-generate-rpm
