ARG UBUNTU_VERSION=22.04
FROM ubuntu:${UBUNTU_VERSION}

USER root

RUN apt-get -y update 
RUN apt-get -y install \
	sudo pkg-config git gcc g++ openssl libssl-dev clang curl make cmake protobuf-compiler 
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:$PATH"
RUN rustup default stable
RUN cargo install cargo-generate-rpm
RUN cargo install cargo-deb
