name: Build Docker Images

on:
  workflow_call:
    inputs:
      upload_url:
        required: true
        type: string
      tag_name:
        required: true
        type: string
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        os: [debian, ubuntu, rockylinux]
        version: [8, 9, 11, 12, 20, 22, 24]
        exclude:
          - os: debian
            version: 8
          - os: debian
            version: 9
          - os: debian
            version: 20
          - os: debian
            version: 22
          - os: debian
            version: 24
          - os: ubuntu
            version: 8
          - os: ubuntu
            version: 9
          - os: ubuntu
            version: 11
          - os: ubuntu
            version: 12
          - os: rockylinux
            version: 11
          - os: rockylinux
            version: 12
          - os: rockylinux
            version: 20
          - os: rockylinux
            version: 22
          - os: rockylinux
            version: 24

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          platforms: linux/amd64
          tags: ghcr.io/letoille/axonmq/${{ matrix.os }}-${{ matrix.version }}:${{ github.ref_name }}
          file: .github/docker/Dockerfile_${{ matrix.os }}
          context: .
          build-args: |
            VERSION=${{ matrix.version }}