name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Rust toolchain
      run: rustup default stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"

    - name: Run cargo check
      run: cargo check --all-targets

    - name: Run cargo test
      run: cargo test --all-targets
