name: axonmq debian

on:
  workflow_call:
    inputs:
      upload_url:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      branch_name:
        required: false
        type: string
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    strategy:
      matrix:
        version: [11, 12]
    container: ghcr.io/letoille/axonmq/debian-${{ matrix.version }}:${{ inputs.branch_name || github.ref_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: rustup default stable
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "linux-debian-${{ matrix.version }}"
        shared-key: ""
        key: ""
        env-vars: ""
        workspaces: ""
        cache-directories: ""
        cache-targets: ""
        cache-on-failure: "true"
        cache-all-crates: ""
        save-if: ${{ github.ref == 'refs/heads/main' }}
        cache-provider: "buildjet"

    - name: Build
      run: |
        cargo build --release
      
    - name: package
      run: |
        cargo deb --no-build

    - name: rename
      if: github.event_name != 'workflow_dispatch'
      run: |
        mv ./target/debian/axonmq_${{ inputs.tag_name }}-1_amd64.deb ./target/debian/axonmq-debian-${{ matrix.version }}-${{ inputs.tag_name }}-1_amd64.deb
    - name: Upload Release Assets
      if: github.event_name != 'workflow_dispatch'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./target/debian/axonmq-debian-${{ matrix.version }}-${{ inputs.tag_name }}-1_amd64.deb

    - name: Upload Deb artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: debian-${{ matrix.version }}-axonmq
        path: target/debian/axonmq_*-1_amd64.deb

