name: axonmq debian

on:
  workflow_call:
    inputs:
      upload_url:
        required: true
        type: string
      tag_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 11, 12]
    container: ghcr.io/axonmq/build-debian${{ matrix.version }}:${{ github.ref_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: rustup default stable
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "linux-debian${{ matrix.version }}"
        shared-key: ""
        key: ""
        env-vars: ""
        workspaces: ""
        cache-directories: ""
        cache-targets: ""
        cache-on-failure: "true"
        cache-all-crates: ""
        save-if: ${{ github.ref == 'refs/heads/main' }}
        cache-provider: "buildjet"
    - name: Build
      run: |
        cargo build --release
        cargo generate-rpm -p axonmq
        ls -l target/generate-rpm/
        ldd --version

    - name: package
      run: |
        cargo deb --no-build
        ls -lh target/debian/
        mv target/debian/axonmq_${{ env.VERSION }}-1_amd64.deb axonmq_${{ env.VERSION }}-1_amd64.deb

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ inputs.upload_url }}
        files: |
          ./axonmq-${{ env.VERSION }}-amd64.deb
          ./target/generate-rpm/axonmq-${{ env.VERSION }}-1.x86_64.rpm

    
