name: Image debian

on: workflow_dispatch

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: [10, 11, 12]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          platforms: linux/amd64
          tags: ghcr.io/letoille/build-asonmq-debian${{ matrix.version }}:${{ github.ref_name }}
          file: .github/docker/Dockerfile_debian
          context: .
          build-args: |
            DEBIAN_VERSION=${{ matrix.version }}
