name: axonmq centos

on: workflow_dispatch

env:
  VERSION: 0.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 11]
    container: ghcr.io/axonmq/build-debian${{ matrix.version }}:${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v4
    - run: rustup default stable
    #- run: rustup target add aarch64-unknown-linux-gnu
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "linux-debian${{ matrix.version }}"
        shared-key: ""
        key: ""
        env-vars: ""
        workspaces: ""
        cache-directories: ""
        cache-targets: ""
        cache-on-failure: "true"
        cache-all-crates: ""
        save-if: ${{ github.ref == 'refs/heads/main' }}
        cache-provider: "buildjet"
    - name: Build
      run: |
        cargo build --release
        cargo generate-rpm -p axonmq
        ls -l target/generate-rpm/
        ldd --version

    - name: upload amd64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: centos-${{ matrix.version }}-amd64-axonmq
        path: |
          target/generate-rpm/axonmq-${{ env.VERSION }}-1.x86_64.rpm
